### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by mxku** [hazelcast/big-data-benchmark#5]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project jet-word-count: Compilation failure
[ERROR] /Users/manish/Downloads/big-data-benchmark/word-count/jet-word-count/src/main/java/com/hazelcast/jet/benchmark/wordcount/JetWordCount.java:[46,16] error: method flatMap in class Processors cannot be applied to given types;
[ERROR] -> [Help 1]

**Comment by cangencer** [comment]
The project was pointing to 0.4-SNAPSHOT, and now have been updated to 0.4. Also make sure you are using latest JDK8 version for compiling.

**Comment by mxku** [comment]
Compilation fine now
